spring:
  application:
    name: busanzip

  datasource:
    url: jdbc:mysql://localhost:3306/busanzip_dev
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create

#baseurl:
#  restaurant: http://apis.data.go.kr/6260000/FoodService/getFoodKr?
#  tourist-attraction: http://apis.data.go.kr/6260000/AttractionService/getAttractionKr?
#
#serviceKey: ${DATA_SERVICEKEY}
